config/routes.rb
TravelTime::Application.routes.draw do



  root 'sessions#home' , as: 'home'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :photos
  resources :comments

  get '/home/login' => 'home#login'
  post '/home/add/' => 'photos#add'
  get  '/home/add/' => 'photos#add'
  post '/users/:id/add' => 'users#add_photo', as: 'adding_photo'
  get '/sign-up' => 'sessions#sign_up', as: 'sign_up'
  get '/users/:id/gallery' => 'users#gallery', as: 'loading_gallery'
  get '/users/:id/maps' => 'users#maps', as: 'loading_maps'
  get '/users/:id/destroy' => 'users#destroy' , as: 'user_destroy'
  get '/users/:id/search' => 'users#search_users' , as: 'user_search'




  get '/test'  => 'photos#test'
  get '/ppal' => 'users#ppal'
  get '/ajax' => 'users#ajax'


  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'   # Request HTTP
  match '/sessions', to: 'sessions#create',     via: 'get'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :photos
  has_many :comments
  has_attached_file :avatar, :styles => { :small => '100x100>', :thumb => '100x100>' }, :default_url => '/images/:style/missing.png'
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  before_create :create_remember_token

  def self.search(query)
    # where(:title, query) -> This would return an exact match of the query
    where('name like ?', "%#{query}%")
  end

  def self.latest
    User.order(:updated_at).last
  end

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end


  private

  def create_remember_token
    self.remember_token = User.digest(User.new_remember_token)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, :set_user , only: [:show, :edit, :update, :destroy, :gallery]
  #before_action :set_user, only: [:show, :edit, :update, :destroy]
  include SessionsHelper
  # GET /users
  # GET /users.json

  def index
    @users = User.all
    @photos = Photo.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @comment = Comment.new
    @user = User.all
    @user_comments = Comment.order(:created_at).reverse_order
    print 'ID DEL CURRENT_USER == >' + String(current_user.id)
  end

  def search_users
    search = params[:search]
    print 'This is what we are looking for' + String(search)
    if params[:search]
      @users_result = User.search(params[:search]).order('created_at')
    end
    render :layout => 'search'
  end

  def add_photo
    @photo = Photo.new
    @us_id = params[:id]
    @user_comments = Comment.order(:created_at).reverse_order
    respond_to do |format|
      format.js {render :layout => false}
    end
  end

  # GET /users/new
  def new
    print 'Entering show function'
    @user = User.new
    puts @photos
  end

  # GET /users/1/edit
  def edit
    render layout: false
  end

  def gallery
    @photos = Photo.all
    print 'Galery'
    @user = User.all
    render 'users-gallery'
  end

  def maps
    render 'user-map'
  end


  # POST /users
  # POST /users.json
  def create
    print 'Creando usuario ==> '
    print user_params
    @user = User.create(user_params)
    respond_to do |format|
      if @user.save
        sign_in @user
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if current_user.update(user_params)
        format.html { redirect_to user_path(current_user), notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
    def destroy
      print 'This is the current user that we are going to delete' + String(current_user.id)
      sign_out
      print 'This is the current user that we are deleting' + String(current_user)
      redirect_to home_path
    end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation, :photo, :avatar, :current_user)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user, :url => user_path(current_user), :html => { :multipart => true } do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>

  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :photo %><br>
    <%= f.text_field :photo %>
  </div>
  <div>
    <%= f.file_field :avatar %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/add_photo.html.erb
<%= form_for @photo, :url => photos_path, :html => { :multipart => true } do |f| %>
    <% if @photo.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@photo.errors.count, 'error') %> prohibited this photo from being saved:</h2>

          <ul>
            <% @photo.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>
    <div>
      <%= f.file_field :avatar %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/users/add_photo.js.erb
$('#modal_add_image').css('display','visible');
$('#modal_add_image').html("<%= escape_javascript render('photos/form') %>");

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/gallery.js.erb
<%= print 'js js js js js js js js' %>
$('#user-container').html("<%= escape_javascript render('gallery') %>");

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Photo</th>
      <th>Avatar</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.photo %></td>
        <td><%= user.avatar_file_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/ppal.html.erb
<div class='user-main-header'>Header</div>

app/views/users/search_users.html.erb
<div class='search-content'>
  <% @users_result.each do |user| %>
      <div class='searched-user'>
          <%= image_tag user.avatar_file_name , :class => 'user-img_style', :id => 'jquery'%>
          <span class='search-name-style'><%= user.name  %></span>
          <div class='search-options'>Follow</div>
      </div>
      <br>
  <% end %>
</div>

app/views/users/show.html.erb
                    <!-- USER CONTAINER -->
 <script>
     $(document).ready(function(){
        //select the div tag with 'addphoto' id
         $('#addphoto2').click(function(event) {
             event.preventDefault();
             //get the div tag
             var addphoto = $(this);

             var maskHeight = '300px'
             var maskWidth = '400px'

             $('#popup').css({'width':maskWidth,'height':maskHeight});

             $('#popup').fadeIn(1000);
             $('#popup').fadeTo("fast",0.8);
             $('#popup').append('<%= link_to 'Add Photo', adding_photo_path(current_user), :id =>'add-photo-mw'%>');

             var winH = $(window).height();
             var winW = $(window).width();

             $(addphoto).css('top', winH/2-$(addphoto).height()/2);
             $(addphoto).css('left', winW/2-$(addphoto).width()/2);

             $(addphoto).fadeIn(2000);
         });
     });

     $(document).ready(function() {
         //select all the a tag with name equal to modal
         $('a[name=modal]').click(function(e) {
             //Cancel the link behavior
             e.preventDefault();
             //Get the A tag
             var id = $(this).attr('href');


             //Get the screen height and width
             var maskHeight = '200px'
             var maskWidth = '200px'

             //Set height and width to mask to fill up the whole screen
             $('#mask').css({'width':maskWidth,'height':maskHeight});

             //transition effect
             $('#mask').fadeIn(1000);
             $('#mask').fadeTo("fast",0.8);

             //Get the window height and width
             var winH = $(window).height();
             var winW = $(window).width();
             //Set the popup window to center
             $(id).css('top', winH/2-$(id).height()/2);
             $(id).css('left', winW/2-$(id).width()/2);

             //transition effect
             $(id).fadeIn(2000);

         });

         //if close button is clicked
         $('.window .close').click(function (e) {
             //Cancel the link behavior
             e.preventDefault();
             $('#mask, .window').hide();
         });

         //if mask is clicked
         $('#mask').click(function () {
             $(this).hide();
             $('.window').hide();
         });

     });
 </script>

  <div class='new-post'>
    <%= form_for @comment , remote: true  do |f| %>
        <% if @comment.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@comment.errors.count, 'error') %> prohibited this comment from being saved:</h2>

              <ul>
                <% @comment.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>
      <p style= 'padding-top:10px;'>
          <%= f.text_field :text , class:'form-control', required:'', placeholder: 'What is your plan?',style:   'display:table-cell'%>
          <%= f.submit 'Post', class: 'btn', style: 'display:table-cell'   %>
          <div id='addphoto2'>Add</div>
          <div id='popup'></div>

        <a href="#dialog" name="modal">Simple Modal Window</a>
        <div id="boxes">

          <!-- #customize your modal window here -->
          <div id="dialog" class="window">
            <b>Testing of Modal Window</b> |

            <!-- close button is defined as close class -->
            <a href="#" class="close">Close it</a>
          </div>

          <!-- Do not remove div#mask, because you'll need it to fill the whole screen -->
          <div id="mask"></div>
        </div>

        <%= link_to 'Add Photo', adding_photo_path(current_user), :id =>'addphoto', remote: true %>
      </p>

    <% end %>

    <div id= 'user-comments'>
        <% @user_comments.take(9).each do |comment|%>
          <% if current_user.id == comment.users_id %>
              <div class='user-comments'>
                <%= comment.text %>
              </div>
          <% end %>
        <% end %>
    </div>
  </div>

app/views/users/show.js.erb
$('#user-container').html("<%= escape_javascript render('users/change') %>");

app/views/users/user-map.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Panoramio Widget API</title>
  <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
  <meta charset="utf-8">
  <style>
      html, body, #map-canvas {
          height: 50%;
          margin: 0px;
      }
  </style>
  <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=panoramio"></script>
  <script src="https://ssl.panoramio.com/wapi/wapi.js?v=1"></script>
  <script>
      function initialize() {
          // The photoDiv defines the DIV within the info window for
          // displaying the Panoramio photo within its PhotoWidget.
          var photoDiv =  document.createElement('div');

          // The PhotoWidget width and height are expressed as number values,
          // not string values.
          var photoWidgetOptions = {
              width: 640,
              height: 500
          };

          // We construct a PhotoWidget here with a blank (null) request as we
          // don't yet have a photo to populate it.
          var photoWidget = new panoramio.PhotoWidget(photoDiv, null,
                  photoWidgetOptions);

          var monoLake = new google.maps.LatLng(37.973432, -119.093170);
          var mapOptions = {
              zoom: 11,
              center: monoLake
          };

          var map = new google.maps.Map(document.getElementById('map-canvas'),
                  mapOptions);

          var infoWindow = new google.maps.InfoWindow();
          var panoramioLayer = new google.maps.panoramio.PanoramioLayer({
              suppressInfoWindows: true
          });

          panoramioLayer.setMap(map);

          google.maps.event.addListener(panoramioLayer, 'click', function(e) {
              var photoRequestOptions = {
                  ids: [{
                      'photoId': e.featureDetails.photoId,
                      'userId': e.featureDetails.userId
                  }]
              };
              photoWidget.setRequest(photoRequestOptions);
              photoWidget.setPosition(0);
              infoWindow.setPosition(e.latLng);
              infoWindow.open(map);
              infoWindow.setContent(photoDiv);
          });
      }

      google.maps.event.addDomListener(window, 'load', initialize);

  </script>
</head>
<body>
<div id="map-canvas"></div>
</body>
</html>

app/views/users/user.js.erb
$('#user-container').html("<%= escape_javascript render('users/comment') %>");

app/views/users/users-gallery.html.erb
<% cache ['photos', Photo.latest] do %>
    <% @photos.each do |photo| %>
        <% if current_user.id == photo.user_id %>
            <% if photo.avatar_file_name == nil %>
                 <%= print 'no PHOTO' %>
                 <%= image_tag 'missing.png', class:'img-gallery' %>
            <% else %>
                <%= image_tag photo.avatar.url, class:'img-gallery' %>
            <% end %>
        <% end %>
    <% end %>
<% end %>
<%= link_to(image_tag('+_icon.png'), adding_photo_path(current_user), :id => 'add_img', method: :post, remote:true)%>
<div id ='modal_add_image'></div>