config/routes.rb
TravelTime::Application.routes.draw do



  root 'sessions#home' , as: 'home'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :photos
  resources :comments

  get '/home/login' => 'home#login'
  post '/home/add/' => 'photos#add'
  get  '/home/add/' => 'photos#add'
  post '/users/:id/add' => 'users#add_photo', as: 'adding_photo'
  get '/sign-up' => 'sessions#sign_up', as: 'sign_up'
  get '/users/:id/gallery' => 'users#gallery', as: 'loading_gallery'
  get '/users/:id/maps' => 'users#maps', as: 'loading_maps'
  get '/users/:id/destroy' => 'users#destroy' , as: 'user_destroy'
  get '/users/:id/search' => 'users#search_users' , as: 'user_search'




  get '/test'  => 'photos#test'
  get '/ppal' => 'users#ppal'
  get '/ajax' => 'users#ajax'


  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'   # Request HTTP
  match '/sessions', to: 'sessions#create',     via: 'get'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TravelTime</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>

</body>
</html>

app/views/layouts/comments-layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    'sessions', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'bootstrap', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <title> Welcome to TravelTime</title>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/home-layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag 'home', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <title>UUUUUu</title>

</head>
<body>

<%= yield %>


</body>
</html>

app/views/layouts/search.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Search</title>
  <%= stylesheet_link_tag    'users', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'bootstrap', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/session-layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    'sessions', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'bootstrap', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <title> Welcome to TravelTime</title>
</head>
<body>

<%= yield %>

</body>
</html>

<!--<%= stylesheet_link_tag    'home/style', media: 'all', 'data-turbolinks-track' => true %>-->
<!--<%= stylesheet_link_tag    'home/jquery.jscrollpane', media: 'all', 'data-turbolinks-track' => true %> -->
<!-- ESTYLES FOR HTML5 -->
<!--<%= stylesheet_link_tag    'html5/skel-noscript', media: 'all', 'data-turbolinks-track' => true %>-->
<!--<%= stylesheet_link_tag    'html5/style', media: 'all', 'data-turbolinks-track' => true %>  -->
<!--<%= stylesheet_link_tag    'html5/style-wide', media: 'all', 'data-turbolinks-track' => true %> -->
<!--<%= stylesheet_link_tag    'html5/ie9', media: 'all', 'data-turbolinks-track' => true %>-->
<!--<%= stylesheet_link_tag    'html5/ie8', media: 'all', 'data-turbolinks-track' => true %> -->

app/views/layouts/user-layout.html.erb
<!DOCTYPE html>
<html>
<script>
  $('#jquery').click(function(){
      $(this).append(" <b>Appended text</b>.");
  });




</script>

<head>
  <title><%= current_user.name %></title>
  <%= stylesheet_link_tag    'users', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'bootstrap', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <p class="navbar-text">Travel Time</p>
  <div class="container-fluid">
    <form class="navbar-form navbar-right" role="search">
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Search">
      </div>
      <button type="submit" class="btn btn-default">Submit Does not work yet</button>
      <div class="btn-group btn-group-lg"><%= link_to 'Log out', user_path , method: :delete%></div>
      <button id='asking'>Form</button>
      <div class="btn-group">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
          Action <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
          <li><a href="#">Action</a></li>
          <li><a href="#">Another action</a></li>
          <li><a href="#">Something else here</a></li>
          <li class="divider"></li>
          <li><a href="#">Separated link</a></li>
        </ul>
      </div>
    </form>
  </div><!-- /.container-fluid -->
</nav>
                                                                          <!-- onclick:'alert("Inline Javscript")' -->

<div class="user-header">

  <span class='user-name'><%= current_user.name  %> </span>
  <div id='avatar-img'>
  <%= image_tag current_user.avatar_file_name , :class => 'user-img_style', :id => 'jquery'%>

  </div>
  <!--<p><a href="#" onclick="document.getElementById('hiddenForm').style.display = 'block'; return false;">Add a message</a></p>-->
  <form action="#" id="hiddenForm" style="display: none;">
    <textarea cols="50" rows="10"></textarea><br />
    <input type="submit" value="send a message" />
  </form>
  <div id='links'>
      <div class='blank-space'></div>
      <%= link_to 'Menu', user_path(current_user.id), class:'css3button'%>
      <div class='blank-space'></div>
      <%= link_to 'Go to Gallery', loading_gallery_path, class:'css3button', :id => 'show-add' %>
      <div class='blank-space'></div>
      <%= link_to 'Go to Maps', loading_maps_path, class:'css3button'%>
      <div class='blank-space'></div>
  </div>
</div>

<div id='user-container' class='user-container' >
<%= yield %>
</div>

</body>
</html>

app/views/layouts/users.html.erb
<!DOCTYPE html>
<html>
<script>
  $('#jquery').click(function(){
      $(this).append(" <b>Appended text</b>.");
  });
</script>

<head>
  <title><%= current_user.name %></title>
  <%= stylesheet_link_tag    'users', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'bootstrap', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <p class="navbar-text">Travel Time</p>
  <div class="container-fluid">
    <%= form_tag(user_search_path, :method => 'get', class: 'navbar-form', id: 'search-form') do %>
        <div class="input-append">
          <%= text_field_tag :search, params[:search], class: 'span2', placeholder: 'Search Users' %>
          <!-- In order to have the "search" icon int the button, we need to use plain HTML instead
               of using a Rails form helper -->
          <button class="btn" type="submit"><i class="icon-search"></i></button>
        </div>
    <% end %>
  </div><!-- /.container-fluid -->
</nav>
                                                                          <!-- onclick:'alert("Inline Javscript")' -->

<div class="user-header">

  <span class='user-name'><%= current_user.name  %></span>
  <div id='avatar-img'>
  <%= image_tag current_user.avatar_file_name , :class => 'user-img_style', :id => 'jquery'%>

  </div>
  <!--<p><a href="#" onclick="document.getElementById('hiddenForm').style.display = 'block'; return false;">Add a message</a></p>-->
  <form action="#" id="hiddenForm" style="display: none;">
    <textarea cols="50" rows="10"></textarea><br />
    <input type="submit" value="send a message" />
  </form>
  <div id='links'>
      <div class='blank-space'></div>
      <%= link_to 'Menu', user_path(current_user.id), class:'css3button'%>
      <div class='blank-space'></div>
      <%= link_to 'Go to Gallery', loading_gallery_path, class:'css3button', :id => 'show-add' %>
      <div class='blank-space'></div>
      <%= link_to 'Go to Maps', loading_maps_path, class:'css3button'%>
      <div class='blank-space'></div>
  </div>
</div>

<div id='user-container' class='user-container' >
<%= yield %>
</div>

</body>
</html>